homeassistant:
    # Name of the location where Home Assistant is running
    name: Home

    # Location required to calculate the time the sun rises and sets
    latitude: 55.695975
    longitude: 12.446366

    # Impacts weather/sunrise data (altitude above sea level in meters)
    elevation: 19

    # metric for Metric, imperial for Imperial
    unit_system: metric
    # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
    time_zone: Europe/Copenhagen

    customize:
        # Heating
        climate.danfoss_z_thermostat_014g0013_heating_1_3_1:
            friendly_name: Danfoss Stuen
        climate.danfoss_z_thermostat_014g0013_heating_1_4_1:
            friendly_name: Danfoss Entreen

        # Logicsoft buttons
        switch.logic_soft_zhc5010_wall_switch_switch_5_0:
            friendly_name: Logicsoft main
        switch.logic_soft_zhc5010_wall_switch_switch_5_0_2:
            friendly_name: Knap 1
        switch.logic_soft_zhc5010_wall_switch_switch_5_0_3:
            friendly_name: Knap 2
        switch.logic_soft_zhc5010_wall_switch_switch_5_0_4:
            friendly_name: Knap 3
        switch.logic_soft_zhc5010_wall_switch_switch_5_0_5:
            friendly_name: Knap 4

# Show links to resources in log and frontend
introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  # Uncomment this to add a password (recommended!)
  api_password: !secret http_password
  # Uncomment this if you are using SSL or running in Docker etc
  # base_url: example.duckdns.org:8123

# Checks for available updates
updater:

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

# Weather Prediction
sensor:
    platform: yr

# Text to speech
tts:
    platform: google

group: !include groups.yaml

mqtt:
    broker: 192.168.1.140
    port: 1883
    username: sykokaj
    password: mefdef17
#    certificate: auto

automation: !include automation.yaml

device_tracker:
    - platform: linksys_ap
      host: 192.168.1.1
      username: admin
      password: !secret linksys_password
      scan_interval: 6
#    - platform: owntracks
#      max_gps_accuracy: 500


#
#device_tracker:
#    - platform: nmap_tracker
#      hosts: 192.168.1.1/24
#      exclude:
#          - 192.168.1.1     #router
#          - 192.168.1.110   #Sonos Play:3
#          - 192.168.1.112   #Pi wifi
#          - 192.168.1.120   #Sonos Playbar
#          - 192.168.1.124   #Sonos Play:5
#          - 192.168.1.140   #Pi
#          - 192.168.1.148   #Ukendt

# tradfri:
#     host: 192.168.1.149
#     api_key: N7abTNn16i2ly1Uw

zwave:
    usb_path: /dev/ttyAMA0
    config_path: /home/homeassistant/.homeassistant/config
#  autoheal: true
#  debug: false

#media_player:
#    - platform: philips_js
#      host: 192.168.1.117
