homeassistant:
    # Name of the location where Home Assistant is running
    name: Home

    # Location required to calculate the time the sun rises and sets
    latitude: 55.6806
    longitude: 12.4537

    # Impacts weather/sunrise data (altitude above sea level in meters)
    elevation: 19

    # metric for Metric, imperial for Imperial
    unit_system: metric
    # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
    time_zone: Europe/Copenhagen

    customize:
        # Heating
        climate.danfoss_z_thermostat_014g0013_heating_1_3_1:
            friendly_name: Danfoss Stuen
        climate.danfoss_z_thermostat_014g0013_heating_1_4_1:
            friendly_name: Danfoss Entreen

        # Logicsoft buttons
        switch.logic_soft_zhc5010_wall_switch_switch_5_0:
            friendly_name: Logicsoft main
        switch.logic_soft_zhc5010_wall_switch_switch_5_0_2:
            friendly_name: Knap 1
        switch.logic_soft_zhc5010_wall_switch_switch_5_0_3:
            friendly_name: Knap 2
        switch.logic_soft_zhc5010_wall_switch_switch_5_0_4:
            friendly_name: Knap 3
        switch.logic_soft_zhc5010_wall_switch_switch_5_0_5:
            friendly_name: Knap 4

# automation:
#trigger:
    #platform: state
    #entity_id: switch.logic_soft_zhc5010_wall_switch_switch_4_0_3
    #to: 'on'
  #action:
    #service: light.turn_on
    #entity_id: light.room001

# Show links to resources in log and frontend
introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  # Uncomment this to add a password (recommended!)
  # api_password: PASSWORD
  # Uncomment this if you are using SSL or running in Docker etc
  # base_url: example.duckdns.org:8123

# Checks for available updates
updater:

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

# Weather Prediction
sensor:
    platform: yr

# Text to speech
tts:
    platform: google

group: !include groups.yaml

zwave:
    usb_path: /dev/ttyAMA0
    config_path: /home/homeassistant/.homeassistant/config
#  autoheal: true
#  debug: false
#  device_config:
#    climate.danfoss_z_thermostat_014g0013_heating_1_3_1:
#      friendly_name: "Danfoss Stuen"
#    climate.danfoss_z_thermostat_014g0013_heating_1_4_1:
#      friendly_name: "Danfoss Entre"
